# rootPath/config/config.yaml
boss:
  sayHi: "您好,我有7年工作经验,还有AIGC大模型、Java,Python,Golang和运维的相关经验,希望应聘这个岗位,期待可以与您进一步沟通,谢谢！"
  debugger: false
  keywords: 
    - "Java"
    - "大模型工程师"
  cityCode:
    - "101280600"
    - "101280600"
  customCityCode: {}
  industry:
    - ""
  experience:
    - ""
  jobType: ""
  salary:
    - ""  # 改为数组形式
  degree:
    - ""
  scale:
    - ""
  stage:
    - ""
  enableAI: false
  filterDeadHR: false
  sendImgResume: false
  expectedSalary:
    - 28
  waitTime: "3s"
  deadStatus: []